name: Build, Test And Deploy Impact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
    - name: Test Impact.Core.Tests
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/Tests/Impact.Core.Tests      
    - name: Test Impact.Consumer.Tests
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/Tests/Impact.Consumer.Tests      
    - name: Test Impact.Consumer.Tests
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/Tests/Impact.Consumer.Tests
    - name: "Package Impact.Core"
      if: github.ref == 'refs/heads/master'
      run: dotnet pack --configuration Release --no-restore
      working-directory: src/Impact.Core
    - name: "Package Impact.Core.Payload.Json"
      if: github.ref == 'refs/heads/master'
      run: dotnet pack --configuration Release --no-restore
      working-directory: src/Impact.Core.Payload.Json
    - name: "Package Impact.Core.Payload.Protobuf"
      if: github.ref == 'refs/heads/master'
      run: dotnet pack --configuration Release --no-restore
      working-directory: src/Impact.Core.Payload.Protobuf
    - name: "Package Impact.Core.Transport.Http"
      if: github.ref == 'refs/heads/master'
      run: dotnet pack --configuration Release --no-restore
      working-directory: src/Impact.Core.Transport.Http
    - name: "Package Impact.Consumer"
      if: github.ref == 'refs/heads/master'
      run: dotnet pack --configuration Release --no-restore
      working-directory: src/Impact.Consumer
    - name: "Package Impact.Consumer.Transport.Http"
      if: github.ref == 'refs/heads/master'
      run: dotnet pack --configuration Release --no-restore
      working-directory: src/Impact.Consumer.Transport.Http
    - name: "Package Impact.Provider"
      if: github.ref == 'refs/heads/master'
      run: dotnet pack --configuration Release --no-restore
      working-directory: src/Impact.Provider
    - name: "Package Impact.Provider.Transport.Http"
      if: github.ref == 'refs/heads/master'
      run: dotnet pack --configuration Release --no-restore
      working-directory: src/Impact.Provider.Transport.Http
    - name: "Publish packages"
      if: github.ref == 'refs/heads/master'
      run: "dotnet nuget push **/*.nupkg -k ${{secrets.nuget_access_key}} -s https://api.nuget.org/v3/index.json --skip-duplicate"
      working-directory: src