// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: weatherforecast.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Impact.Samples.ProtobufOverHttp.Model {

  /// <summary>Holder for reflection information generated from weatherforecast.proto</summary>
  public static partial class WeatherforecastReflection {

    #region Descriptor
    /// <summary>File descriptor for weatherforecast.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WeatherforecastReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChV3ZWF0aGVyZm9yZWNhc3QucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1l",
            "c3RhbXAucHJvdG8ihgEKD1dlYXRoZXJGb3JlY2FzdBIMCgRDaXR5GAEgASgJ",
            "EhQKDFRlbXBlcmF0dXJlQxgCIAEoBRIUCgxUZW1wZXJhdHVyZUYYAyABKAUS",
            "DwoHU3VtbWFyeRgEIAEoCRIoCgREYXRlGAUgASgLMhouZ29vZ2xlLnByb3Rv",
            "YnVmLlRpbWVzdGFtcEIoqgIlSW1wYWN0LlNhbXBsZXMuUHJvdG9idWZPdmVy",
            "SHR0cC5Nb2RlbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Impact.Samples.ProtobufOverHttp.Model.WeatherForecast), global::Impact.Samples.ProtobufOverHttp.Model.WeatherForecast.Parser, new[]{ "City", "TemperatureC", "TemperatureF", "Summary", "Date" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class WeatherForecast : pb::IMessage<WeatherForecast> {
    private static readonly pb::MessageParser<WeatherForecast> _parser = new pb::MessageParser<WeatherForecast>(() => new WeatherForecast());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WeatherForecast> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Impact.Samples.ProtobufOverHttp.Model.WeatherforecastReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeatherForecast() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeatherForecast(WeatherForecast other) : this() {
      city_ = other.city_;
      temperatureC_ = other.temperatureC_;
      temperatureF_ = other.temperatureF_;
      summary_ = other.summary_;
      date_ = other.date_ != null ? other.date_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WeatherForecast Clone() {
      return new WeatherForecast(this);
    }

    /// <summary>Field number for the "City" field.</summary>
    public const int CityFieldNumber = 1;
    private string city_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string City {
      get { return city_; }
      set {
        city_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TemperatureC" field.</summary>
    public const int TemperatureCFieldNumber = 2;
    private int temperatureC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TemperatureC {
      get { return temperatureC_; }
      set {
        temperatureC_ = value;
      }
    }

    /// <summary>Field number for the "TemperatureF" field.</summary>
    public const int TemperatureFFieldNumber = 3;
    private int temperatureF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TemperatureF {
      get { return temperatureF_; }
      set {
        temperatureF_ = value;
      }
    }

    /// <summary>Field number for the "Summary" field.</summary>
    public const int SummaryFieldNumber = 4;
    private string summary_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Summary {
      get { return summary_; }
      set {
        summary_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Date" field.</summary>
    public const int DateFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp date_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Date {
      get { return date_; }
      set {
        date_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WeatherForecast);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WeatherForecast other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (City != other.City) return false;
      if (TemperatureC != other.TemperatureC) return false;
      if (TemperatureF != other.TemperatureF) return false;
      if (Summary != other.Summary) return false;
      if (!object.Equals(Date, other.Date)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (City.Length != 0) hash ^= City.GetHashCode();
      if (TemperatureC != 0) hash ^= TemperatureC.GetHashCode();
      if (TemperatureF != 0) hash ^= TemperatureF.GetHashCode();
      if (Summary.Length != 0) hash ^= Summary.GetHashCode();
      if (date_ != null) hash ^= Date.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (City.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(City);
      }
      if (TemperatureC != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TemperatureC);
      }
      if (TemperatureF != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TemperatureF);
      }
      if (Summary.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Summary);
      }
      if (date_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Date);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (City.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(City);
      }
      if (TemperatureC != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TemperatureC);
      }
      if (TemperatureF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TemperatureF);
      }
      if (Summary.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Summary);
      }
      if (date_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Date);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WeatherForecast other) {
      if (other == null) {
        return;
      }
      if (other.City.Length != 0) {
        City = other.City;
      }
      if (other.TemperatureC != 0) {
        TemperatureC = other.TemperatureC;
      }
      if (other.TemperatureF != 0) {
        TemperatureF = other.TemperatureF;
      }
      if (other.Summary.Length != 0) {
        Summary = other.Summary;
      }
      if (other.date_ != null) {
        if (date_ == null) {
          Date = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Date.MergeFrom(other.Date);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            City = input.ReadString();
            break;
          }
          case 16: {
            TemperatureC = input.ReadInt32();
            break;
          }
          case 24: {
            TemperatureF = input.ReadInt32();
            break;
          }
          case 34: {
            Summary = input.ReadString();
            break;
          }
          case 42: {
            if (date_ == null) {
              Date = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Date);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
